---
title: "Treatment-control comparisons in platform trials including non-concurrent controls"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repository contains the main code to reproduce the results of the paper "Treatment-control comparisons in platform trials including non-concurrent controls''. 
<!-- "[Treatment-control comparisons in platform trials including non-concurrent controls](https://arxiv.org)". -->

------------------------------------------------------------------------

**Funding**

[EU-PEARL](https://eu-pearl.eu/) (EU Patient-cEntric clinicAl tRial pLatforms) project has received funding from the Innovative Medicines Initiative (IMI) 2 Joint Undertaking (JU) under grant agreement No 853966. This Joint Undertaking receives support from the European Union’s Horizon 2020 research and innovation programme and EFPIA andChildren’s Tumor Foundation, Global Alliance for TB Drug Development non-profit organisation, Spring works Therapeutics Inc. This publication reflects the authors’ views. Neither IMI nor the European Union, EFPIA, or any Associated Partners are responsible for any use that may be made of the information contained herein.

This research was funded in whole or in part by the Austrian Science Fund (FWF) [ESP 442 ESPRIT-Programm].