---
title: "Treatment-control comparisons in platform trials including non-concurrent controls"
author: "Marta Bofill Roig, Pavla Krotka, Katharina Hees, Franz Koenig, Dominic Magirr, Peter Jacko, Tom Parke, Kert Viele, Martin Posch"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: show 
    theme: flatly
---

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE,
               comment = "#>",
               warning = FALSE,
               message = FALSE,
               echo = FALSE,
               fig.align = "center",
               out.width = "100%")
```

```{r, include=FALSE}
library(tidyverse)
library(ggpubr)
library(scales)
library(latex2exp)
library(NCC)
```


```{r}
# Load in all files from "results"

csv_names <- list.files("results/", pattern="*.csv")

for (i in 1:length(csv_names)){
  assign(str_extract(csv_names[i], "^([^\\.])+"), read_csv(paste0("results/", csv_names[i])) %>%
           mutate(model = as.factor(case_when(model=="fixmodel" ~ "Regression model",
                                              model=="MAPpriorNew" ~ "MAP Prior",
                                              model=="poolmodel" ~ "Pooled approach",
                                              model=="sepmodel" ~ "Separate approach",
                                              model=="timemachine" ~ "Time machine")),
                  trend = case_when(trend=="linear" ~ "Linear time trend",
                                    trend=="stepwise_2" ~ "Stepwise time trend",
                                    trend=="inv_u" ~ "Inverted-U trend"),
                  tau_case = factor(case_when(tau_case=="e-10, m-15" ~ "exp.: 10, max.: 15",
                                              tau_case=="e-5, m-10" ~ "exp.: 5, max.: 10",
                                              tau_case=="e-1, m-1.5" ~ "exp.: 1, max.: 1.5",
                                              tau_case=="e-0.01, m-0.15" ~ "exp.: 0.01, max.: 0.15",
                                              tau_case=="e-0.001, m-0.015" ~ "exp.: 0.001, max.: 0.015",
                                              TRUE ~ tau_case),
                                    levels = c("exp.: 10, max.: 15", "exp.: 5, max.: 10", "exp.: 1, max.: 1.5", "exp.: 0.01, max.: 0.15", "exp.: 0.001, max.: 0.015"))))
}

my_palette = c("MAP Prior" = "#ED0000FF",
               "Pooled approach" = "#42B540FF",
               "Regression model" = "#00468BFF",
               "Separate approach" = "#925E9FFF",
               "Time machine" = "#EEAD0E",
               "exp.: 10, max.: 15" = "mediumorchid3",
               "exp.: 5, max.: 10" = "coral3",
               "exp.: 1, max.: 1.5" = "#1B1919FF",
               "exp.: 0.01, max.: 0.15" = "aquamarine4",
               "exp.: 0.001, max.: 0.015" = "#FDAF91FF",
               `2` =  "lightpink3",
               `0.2` = "darkred",
               `0.002` = "skyblue4")


#show_col(my_palette)

# Prediction interval for T1E
p <- 0.025
alpha <- 0.05
nsim <- 10000
sd <- sqrt(p*(1-p)/nsim)
z.alpha <- qnorm(1-alpha/2,0,1)
pred_int <- c(p-z.alpha*sd,p+z.alpha*sd)
```


```{r, include=FALSE}
# Considered cases for the tau_a and tau_b

from_jump_size_to_tau_a_b <- function(e_jump_size = 0.01, max_jump_size = 0.1){
  
  fun_to_solve <- function(tau_b, max_jump_size, e_jump_size){
    pgamma(1 / max_jump_size ^ 2, 1 / (e_jump_size ^ 2) * tau_b, tau_b) - 0.01
    # pgamma(1 / max_jump_size ^ 2, 1 / (e_jump_size ^ 2) * tau_b, 1/tau_b) - 0.01
  }
  
  tau_b <- uniroot(fun_to_solve,
                   c(1e-12, 1e12),
                   max_jump_size = max_jump_size,
                   e_jump_size = e_jump_size)$root
  
  tau_a <- 1 / e_jump_size ^ 2 * tau_b
  
  c(tau_a = tau_a,
    tau_b = tau_b)
}

from_jump_size_to_tau_a_b(e_jump_size = 10, max_jump_size = 15)

from_jump_size_to_tau_a_b(e_jump_size = 5, max_jump_size = 10)

from_jump_size_to_tau_a_b(e_jump_size = 1, max_jump_size = 1.5)

from_jump_size_to_tau_a_b(e_jump_size = 0.01, max_jump_size = 0.15)

from_jump_size_to_tau_a_b(e_jump_size = 0.001, max_jump_size = 0.015)
```


# Time trend patterns

```{r, fig.width = 4.5, fig.height = 9}
data_lin <- datasim_cont(num_arms = 3, n_arm = 250, d = 250*c(0:2), theta=rep(0, 3), lambda = rep(0.15, 4), sigma = 1, trend = "linear", full = T)$Data

data_step <- datasim_cont(num_arms = 3, n_arm = 250, d = 250*c(0:2), theta=rep(0, 3), lambda = rep(0.15, 4), sigma = 1, trend = "stepwise_2", full = T)$Data

data_inv_u <- datasim_cont(num_arms = 3, n_arm = 250, d = 250*c(0:2), theta=rep(0, 3), lambda = rep(0.15, 4), sigma = 1, trend = "inv_u", N_peak = 605, full = T)$Data

p <- ggarrange(ggplot(data_lin) +
                 geom_point(aes(x=j, y=means), color="#111d4f") +
                 theme_bw() +
                 theme(plot.title = element_text(hjust = 0.5)) +
                 labs(x="Patient recruitment", y=TeX("Mean response under $H_0$"), title = "Linear trend"),
               
               ggplot(data_step) +
                 geom_point(aes(x=j, y=means), color="#111d4f") +
                 theme_bw() +
                 theme(plot.title = element_text(hjust = 0.5)) +
                 labs(x="Patient recruitment", y=TeX("Mean response under $H_0$"), title = "Stepwise trend") +
                 scale_y_continuous(breaks = seq(0, 0.45, by=0.15), labels = seq(0, 0.45, by=0.15)),
               
               ggplot(data_inv_u) +
                 geom_point(aes(x=j, y=means), color="#111d4f") +
                 theme_bw() +
                 theme(plot.title = element_text(hjust = 0.5)) +
                 labs(x="Patient recruitment", y=TeX("Mean response under $H_0$"), title = TeX("Inverted-U trend$")) +
                 scale_y_continuous(breaks = seq(0, 0.075, length.out=4), labels = seq(0, 0.075, length.out=4)),
               nrow = 3)
p

export::graph2eps(x = p, file = "figures/trend_patterns", width = 4.5, height = 9, cairo=TRUE, fallback_resolution=600)

ggsave("figures/trend_patterns.pdf", width = 4.5, height = 9)
ggsave("figures/trend_patterns.png", width = 4.5, height = 9)
```


# Setting I

## Equal time trends (main paper)

```{r, fig.width = 9, fig.height = 7}
p <- ggarrange(ggplot(results_i_eq_alpha %>% filter(trend=="Stepwise time trend"), 
                      aes(color=model, linetype=as.factor(study_arm))) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 facet_grid(.~ trend) +
                 geom_line(aes(d2, reject_h0)) +
                 geom_point(aes(d2, reject_h0)) +
                 labs(x="d", y="Type I error rate", color="Analysis approach:", linetype="Arm under study:") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_i_eq_alpha$d2), labels = unique(results_i_eq_alpha$d2)) + 
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom",
                       legend.box = "vertical"),
               
               ggplot(rbind(results_i_eq_pow) %>% filter(trend=="Stepwise time trend"), aes(color=model, linetype = as.factor(study_arm))) +
                 facet_grid(.~ trend) +
                 geom_line(aes(d2, reject_h0)) +
                 geom_point(aes(d2, reject_h0)) +
                 labs(x="d", y="Power", color="Analysis approach:", linetype="Arm under study:") +
                 coord_cartesian(ylim = c(0.7, 1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_i_eq_pow$d2), labels = unique(results_i_eq_pow$d2)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom",
                       legend.box = "vertical"),
               
               common.legend = T, legend = "bottom") + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/i_eq_alpha_pow_d_main", width = 9, height = 7, cairo=TRUE, fallback_resolution=600)

ggsave("figures/i_eq_alpha_pow_d_main.pdf", width = 9, height = 7)
ggsave("figures/i_eq_alpha_pow_d_main.png", width = 9, height = 7)
```


## Equal time trends (supp. material)

```{r, fig.width = 9, fig.height = 12}
p <- ggarrange(ggplot(results_i_eq_alpha %>% filter(trend!="Stepwise time trend"), aes(color=model, linetype=as.factor(study_arm))) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 facet_grid(.~ trend) +
                 geom_line(aes(d2, reject_h0)) +
                 geom_point(aes(d2, reject_h0)) +
                 labs(x="d", y="Type I error rate", color="Analysis approach:", linetype="Arm under study:") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_i_eq_alpha$d2), labels = unique(results_i_eq_alpha$d2)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom",
                       legend.box = "vertical"),
               
               ggplot(results_i_eq_pow %>% filter(trend!="Stepwise time trend"), aes(color=model, linetype = as.factor(study_arm))) +
                 facet_grid(.~ trend) +
                 geom_line(aes(d2, reject_h0)) +
                 geom_point(aes(d2, reject_h0)) +
                 labs(x="d", y="Power", color="Analysis approach:", linetype="Arm under study:") +
                 coord_cartesian(ylim = c(0.7, 1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_i_eq_pow$d2), labels = unique(results_i_eq_pow$d2)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom",
                       legend.box = "vertical"),
               common.legend = T, legend = "bottom", nrow = 2) + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/i_eq_alpha_pow_d_supp", width = 9, height = 12, cairo=TRUE, fallback_resolution=600)

ggsave("figures/i_eq_alpha_pow_d_supp.pdf", width = 9, height = 12)
ggsave("figures/i_eq_alpha_pow_d_supp.png", width = 9, height = 12)
```

## Time Machine and MAP Prior calibration

```{r, fig.width = 9, fig.height = 7}
p <- ggarrange(ggplot(results_i_eq_alpha_TM %>% filter(model=="Time machine"), 
                      aes(lambda0, reject_h0, color=tau_case)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 facet_grid(.~ trend) +
                 geom_line() +
                 geom_point() +
                 labs(x=TeX("$\\lambda$"), y="Type I error rate", color="Assumed time drifts:") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_eq_alpha_TM$lambda0), max(results_i_eq_alpha_TM$lambda0), by=0.05),
                                    labels = round(seq(min(results_i_eq_alpha_TM$lambda0), max(results_i_eq_alpha_TM$lambda0), by=0.05), 3)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = c(0.32, 0.81),
                       legend.background = element_blank()),
               
               ggplot(results_i_eq_alpha_MAP_weight_allpriors %>% filter(model=="MAP Prior", weight==0.1), 
                      aes(lambda0, reject_h0, color=as.factor(prior_prec_tau), linetype=as.factor(prior_prec_eta))) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 facet_grid(.~ trend) +
                 geom_line() +
                 geom_point() +
                 labs(x=TeX("$\\lambda$"), y="Type I error rate", color=TeX("$1/\\sigma^2_\\tau$:"), linetype=TeX("$1/\\sigma^2_\\beta$:")) +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_eq_alpha_MAP_weight_allpriors$lambda0), max(results_i_eq_alpha_MAP_weight_allpriors$lambda0), by=0.05),
                                    labels = round(seq(min(results_i_eq_alpha_MAP_weight_allpriors$lambda0), max(results_i_eq_alpha_MAP_weight_allpriors$lambda0), by=0.05), 3)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = c(0.15, 0.75),
                       legend.box = "vertical",
                       legend.background = element_blank()))
p

export::graph2eps(x = p, file = "figures/i_eq_alpha_lambda_TM_MAP_main", width = 9, height = 7, cairo=TRUE, fallback_resolution=600)

ggsave("figures/i_eq_alpha_lambda_TM_MAP_main.pdf", width = 9, height = 7)
ggsave("figures/i_eq_alpha_lambda_TM_MAP_main.png", width = 9, height = 7)
```


## Different time trends (main paper)

```{r, fig.width = 9, fig.height = 7}
p <- ggarrange(ggplot(results_i_diff1_alpha %>% filter(trend=="Stepwise time trend"), aes(color=model)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(lambda1, reject_h0)) +
                 geom_point(aes(lambda1, reject_h0)) +
                 labs(x=TeX("$\\lambda_1$"), y="Type I error rate", color="Analysis approach:", title = "A) Different time trend in arm 1") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05),
                                    labels = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05)) +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 theme_bw(base_size = 13.4) +
                 theme(title = element_text(size = 12.5),
                       legend.position = "bottom"),
               
               ggplot(results_i_diff12_alpha %>% filter(trend=="Stepwise time trend"), aes(color=model)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(lambda1, reject_h0)) +
                 geom_point(aes(lambda1, reject_h0)) +
                 labs(x=TeX("$\\lambda_1$"), y="Type I error rate", color="Analysis approach:", title = "B) Different time trends in arms 1 and 2") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05),
                                    labels = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05)) +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 theme_bw(base_size = 13.4) +
                 theme(title = element_text(size = 12.5),
                       legend.position = "bottom"),
               
               common.legend = T, legend = "bottom") + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/i_diff1_diff12_alpha_lambda_main", width = 9, height = 7, cairo=TRUE, fallback_resolution=600)

ggsave("figures/i_diff1_diff12_alpha_lambda_main.pdf", width = 9, height = 7)
ggsave("figures/i_diff1_diff12_alpha_lambda_main.png", width = 9, height = 7)
```

## Different time trends (supp. material)

```{r, fig.width = 9, fig.height = 12}
p <- ggarrange(ggplot(results_i_diff1_alpha %>% filter(trend!="Stepwise time trend"), 
                      aes(color=model)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(lambda1, reject_h0)) +
                 geom_point(aes(lambda1, reject_h0)) +
                 labs(x=TeX("$\\lambda_1$"), y="Type I error rate", color="Analysis approach:", title = "A) Different time trend in arm 1") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05),
                                    labels = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05)) +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom"),
               
               ggplot(results_i_diff12_alpha %>% filter(trend!="Stepwise time trend"), 
                      aes(color=model)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(lambda1, reject_h0)) +
                 geom_point(aes(lambda1, reject_h0)) +
                 labs(x=TeX("$\\lambda_1$"), y="Type I error rate", color="Analysis approach:", title = "B) Different time trends in arms 1 and 2") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05),
                                    labels = seq(min(results_i_diff1_alpha$lambda1), max(results_i_diff1_alpha$lambda1), by=0.05)) +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 theme_bw(base_size = 13.4) +
                 theme(legend.position = "bottom"),
               
               common.legend = T, legend = "bottom", nrow = 2) + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/i_diff1_diff12_alpha_lambda_supp", width = 9, height = 12, cairo=TRUE, fallback_resolution=600)

ggsave("figures/i_diff1_diff12_alpha_lambda_supp.pdf", width = 9, height = 12)
ggsave("figures/i_diff1_diff12_alpha_lambda_supp.png", width = 9, height = 12)
```






# Setting II


```{r, fig.width = 9, fig.height = 12}
p <- ggarrange(ggplot(results_ii_eq_alpha, aes(color=model)) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(d3, reject_h0)) +
                 geom_point(aes(d3, reject_h0)) +
                 labs(x=TeX("$d_3$"), y="Type I error rate", color="Analysis approach:") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_ii_eq_alpha$d3), labels = unique(results_ii_eq_alpha$d3)) +
                 theme_bw(base_size = 13.4),
               
               ggplot(results_ii_eq_pow, aes(color=model)) +
                 geom_line(aes(d3, reject_h0)) +
                 geom_point(aes(d3, reject_h0)) +
                 labs(x=TeX("$d_3$"), y="Power", color="Analysis approach") +
                 coord_cartesian(ylim = c(0.7, 1)) +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = unique(results_ii_eq_pow$d3), labels = unique(results_ii_eq_pow$d3)) +
                 theme_bw(base_size = 13.4),
               
               common.legend = T, legend = "bottom", nrow = 2) + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/ii_eq_alpha_pow_d_main", width = 9, height = 12, cairo=TRUE, fallback_resolution=600)

ggsave("figures/ii_eq_alpha_pow_d_main.pdf", width = 9, height = 12)
ggsave("figures/ii_eq_alpha_pow_d_main.png", width = 9, height = 12)
```






# Setting III


```{r, fig.width = 9, fig.height = 7}
p <- ggarrange(ggplot(results_iii_ii_rand_alpha) +
                 annotate("rect", xmin = -Inf, xmax = Inf, ymin = pred_int[1], ymax = pred_int[2], fill = "gray54", alpha = 0.4) +
                 geom_line(aes(lambda0, reject_h0, color=model)) +
                 geom_point(aes(lambda0, reject_h0, color=model)) +
                 labs(x=TeX("$\\lambda_0 = \\lambda_{10}$"), y="Type I error rate", color="Analysis approach:") +
                 geom_hline(aes(yintercept = 0.025), linetype = "dotted") +
                 coord_cartesian(ylim = c(0, 0.1)) +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_iii_ii_rand_alpha$lambda0), max(results_iii_ii_rand_alpha$lambda0), by=0.05),
                                    labels = round(seq(min(results_iii_ii_rand_alpha$lambda0), max(results_iii_ii_rand_alpha$lambda0), by=0.05), 3)) +
                 theme_bw(base_size = 13.4),
               
               ggplot(results_iii_ii_rand_pow) +
                 geom_line(aes(lambda0, reject_h0, color=model)) +
                 geom_point(aes(lambda0, reject_h0, color=model)) +
                 labs(x=TeX("$\\lambda_0 = \\lambda_{10}$"), y="Power", color="Analysis approach:") +
                 coord_cartesian(ylim = c(0.7, 1)) +
                 facet_grid(~ trend) +
                 scale_color_manual(values = my_palette) +
                 scale_x_continuous(breaks = seq(min(results_iii_ii_rand_alpha$lambda0), max(results_iii_ii_rand_alpha$lambda0), by=0.05),
                                    labels = round(seq(min(results_iii_ii_rand_alpha$lambda0), max(results_iii_ii_rand_alpha$lambda0), by=0.05), 3)) +
                 theme_bw(base_size = 13.4),
               
               common.legend = T, legend = "bottom") + 
  bgcolor("white") + 
  border("white")
p

export::graph2eps(x = p, file = "figures/iii_ii_rand_alpha_pow_lambda_main", width = 9, height = 7, cairo=TRUE, fallback_resolution=600)

ggsave("figures/iii_ii_rand_alpha_pow_lambda_main.pdf", width = 9, height = 7)
ggsave("figures/iii_ii_rand_alpha_pow_lambda_main.png", width = 9, height = 7)
```


















